name: Build Electron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and Package
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/
